#
# File: php73.yml
# Description: PHP 7.x installation playbook
#
---

- import_playbook: locales.yml

- name: "*** PHP 7.x installation playbook"
  hosts: "*"

  #
  # Variables
  #
  vars:
    - packages:
        - 'php7.3-cli'
        - 'php7.3-cgi'
        - 'php7.3-dev'
        - 'php7.3-json'
        - 'php7.3-tidy'
        - 'php7.3-curl'
        - 'php7.3-mbstring'
        - 'php7.3-bcmath'
        - 'php7.3-common'
        - 'php7.3-xml'
        - 'php7.3-zip'
        - 'php7.3-intl'

  #
  # Tasks
  #
  tasks:
    - name: "Add PHP 7.x ppa repository."
      apt_repository: repo=ppa:ondrej/php
      become: yes

    - name: "Install PHP 7.x packages."
      apt: pkg={{ packages }} update_cache=yes state=present
      become: yes

    - name: "Check php.ini file."
      stat: path='/etc/php/7.3/fpm/php.ini'
      become: yes
      register: stat_php_ini

    - name: "Update fpm max execution time."
      lineinfile: dest=/etc/php/7.3/fpm/php.ini regexp='max_execution_time = 30' line='max_execution_time = 300'
      become: yes
      when: stat_php_ini.stat.exists

    - name: "Update fpm memory limit."
      lineinfile: dest=/etc/php/7.3/fpm/php.ini regexp='memory_limit = 128M' line='memory_limit = 256M'
      become: yes
      when: stat_php_ini.stat.exists

    - name: "Update fpm max file size."
      lineinfile: dest=/etc/php/7.3/fpm/php.ini regexp='upload_max_filesize = 2M' line='upload_max_filesize = 20M'
      become: yes
      when: stat_php_ini.stat.exists

    - name: "Update fpm post max size."
      lineinfile: dest=/etc/php/7.3/fpm/php.ini regexp='post_max_size = 8M' line='post_max_size = 20M'
      become: yes
      when: stat_php_ini.stat.exists

    - name: "Fix fpm cgi.fix_pathinfo."
      lineinfile: dest=/etc/php/7.3/fpm/php.ini regexp=';cgi.fix_pathinfo=1' line='cgi.fix_pathinfo=0'
      become: yes
      when: stat_php_ini.stat.exists

    - name: "Update fpm listen."
      lineinfile: dest=/etc/php/7.3/fpm/pool.d/www.conf regexp='listen = /run/php/php7.3-fpm.sock' line='listen = 9000'
      become: yes
      when: stat_php_ini.stat.exists
